[package]
name = "cv_to_ndarray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.64.0"
ndarray = "0.15.4"
anyhow = "1.0.57"
cv-convert = "0.18.0"